name: CI - Ejecutar programa

on:
  push:
    branches:
      - main

jobs:
  ejecutar-programa:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'  

      - name: Instalar dependencias 
        run: |
          pip install -r requirements.txt || echo "No hay dependencias que instalar"

      - name: Ejecutar el programa principal
        run: python main.py
